apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
      product: {{ .Release.Name }}
  replicas: {{ .Values.config.frontend.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
        product: {{ .Release.Name }}
      annotations:
        support.contact: "ace.innovation@dynatrace.com"
        support.channel: "#help-acebox"
    spec:
      containers:
      - env:
        - name: DT_RELEASE_VERSION
          value: {{ .Values.config.frontend.tag }}
        - name: DT_RELEASE_BUILD_VERSION
          value: {{ .Values.config.frontend.tag }}
        - name: DT_RELEASE_STAGE
          value: {{ .Release.Namespace }}
        - name: DT_RELEASE_PRODUCT
          value: {{ .Release.Name }}
        envFrom:
        - configMapRef:
            name: easytravel-config
        # - secretRef:
        #     name: mongo-credentials
        image: dynatrace/easytravel-frontend:{{ .Values.config.frontend.tag }}
        imagePullPolicy: "Always"
        name: {{ .Release.Name }}-frontend
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 150m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 1000Mi
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 30
          initialDelaySeconds: 120
          successThreshold: 1
          timeoutSeconds: 10
      restartPolicy: Always
