apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pluginservice
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pluginservice
      product: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pluginservice
        product: {{ .Release.Name }}
      annotations:
        support.contact: "ace.innovation@dynatrace.com"
        support.channel: "#help-acebox"
    spec:
      containers:
      - env:
        - name: DT_RELEASE_VERSION
          value: {{ .Values.config.pluginservice.tag }}
        - name: DT_RELEASE_BUILD_VERSION
          value: {{ .Values.config.pluginservice.tag }}
        - name: DT_RELEASE_STAGE
          value: {{ .Release.Namespace }}
        - name: DT_RELEASE_PRODUCT
          value: {{ .Release.Name }}
        image: dynatrace/easytravel-pluginservice:{{ .Values.config.pluginservice.tag }}
        imagePullPolicy: "Always"
        name: {{ .Release.Name }}-pluginservice
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 300Mi
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /PluginService/ping
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always
