apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-www
  name: {{ .Release.Name }}-www
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-www
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-www-angular
  name: {{ .Release.Name }}-www-angular
spec:
  ports:
  - protocol: TCP
    targetPort: 9079
    port: 80
  selector:
    app: {{ .Release.Name }}-www
  type: ClusterIP