apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-backend
  name: {{ .Release.Name }}-backend
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-backend
  type: ClusterIP
