---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  ET_BACKEND_URL: http://{{ .Release.Name }}-backend:8080
  ET_FRONTEND_URL: http://{{ .Release.Name }}-www:80
  ET_WWW_URL: http://{{ .Values.config.ingress.domain }}
  ET_ANGULAR_FRONTEND_URL: http://{{ .Values.config.ingress.angular_domain }}
  ET_FRONTEND_LOCATION: {{ .Release.Name }}-frontend:8080
  ET_ANGULAR_FRONTEND_LOCATION: {{ .Release.Name }}-angular-frontend-service:8080
  ET_BACKEND_LOCATION: {{ .Release.Name }}-backend:8080
  ET_PLUGIN_SERVICE_LOCATION: {{ .Release.Name }}-pluginservice:8080
  ET_PROBLEMS: "{{ .Values.config.loadgen.problems }}"
  ET_PROBLEMS_DELAY: "0"
  ET_VISIT_NUMBER: "{{ .Values.config.loadgen.visitNumber }}"
  MAX_CHROME_DRIVERS: "{{ .Values.config.loadgen.visitNumber }}"
  ET_APM_SERVER_DEFAULT: APM
  CATALINA_OPTS: "-Dconfig.apmServerDefault=APM -XX:+UseContainerSupport -XX:MaxRAMPercentage=80 -Djava.security.egd=file:/dev/./urandom"
  ET_DATABASE_LOCATION: easytravel-mongodb:27017
  ET_MONGO_AUTH_DB: admin
  ET_DATABASE_USER: etAdmin
  ET_DATABASE_PASSWORD: adminadmin