apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-mongodb
  name: {{ .Release.Name }}-mongodb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  - name: "28017"
    port: 28017
    targetPort: 28017
  selector:
    app: {{ .Release.Name }}-mongodb
