---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
spec:
  selector:
    matchLabels:
      app: loadgen
      product: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgen
        product: {{ .Release.Name }}
      annotations:
        support.contact: "ace.innovation@dynatrace.com"
        support.channel: "#help-acebox"
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: easytravel-config
        env:
        - name: DT_RELEASE_VERSION
          value: {{ .Values.config.loadgen.tag }}
        - name: DT_RELEASE_BUILD_VERSION
          value: {{ .Values.config.loadgen.tag }}
        - name: DT_RELEASE_STAGE
          value: {{ .Release.Namespace }}
        - name: DT_RELEASE_PRODUCT
          value: {{ .Release.Name }}
        image: dynatrace/easytravel-loadgen:{{ .Values.config.loadgen.tag }}
        name: {{ .Release.Name }}-loadgen
        resources:
          limits:
            cpu: 100m
            memory: 768Mi
          requests:
            cpu: 50m
            memory: 500Mi
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen-angular
spec:
  selector:
    matchLabels:
      app: loadgen-angular
      product: {{ .Release.Name }}
  replicas: {{ .Values.config.loadgen_angular.replicas }}
  template:
    metadata:
      labels:
        app: loadgen-angular
        product: {{ .Release.Name }}
      annotations:
        support.contact: "ace.innovation@dynatrace.com"
        support.channel: "#help-acebox"
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: easytravel-config
        env:
        - name: DT_RELEASE_VERSION
          value: {{ .Values.config.loadgen_angular.tag }}
        - name: DT_RELEASE_BUILD_VERSION
          value: {{ .Values.config.loadgen_angular.tag }}
        - name: DT_RELEASE_STAGE
          value: {{ .Release.Namespace }}
        - name: DT_RELEASE_PRODUCT
          value: {{ .Release.Name }}
        image: dynatrace/easytravel-headless-loadgen:{{ .Values.config.loadgen_angular.tag }}
        name: {{ .Release.Name }}-loadgen-angular
        resources:
          limits:
            cpu: 300m
            memory: 768Mi
          requests:
            cpu: 100m
            memory: 500Mi
      restartPolicy: Always

