---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-angular-frontend
  name: {{ .Release.Name }}-angular-frontend-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: port1
    nodePort: 31080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port2
    nodePort: 31280
    port: 8280
    protocol: TCP
    targetPort: 8280
  selector:
    app: {{ .Release.Name }}-angular-frontend
  sessionAffinity: None
  type: NodePort