apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-www
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-www
      product: {{ .Release.Name }}
  replicas: {{ .Values.config.www.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-www
        product: {{ .Release.Name }}
      annotations:
        support.contact: "ace.innovation@dynatrace.com"
        support.channel: "#help-acebox"
    spec:
      containers:
      - env:
        - name: DT_RELEASE_VERSION
          value: {{ .Values.config.www.tag }}
        - name: DT_RELEASE_BUILD_VERSION
          value: {{ .Values.config.www.tag }}
        - name: DT_RELEASE_STAGE
          value: {{ .Release.Namespace }}
        - name: DT_RELEASE_PRODUCT
          value: {{ .Release.Name }}
        envFrom:
        - configMapRef:
            name: easytravel-config
        image: dynatrace/easytravel-nginx:{{ .Values.config.www.tag }}
        imagePullPolicy: "Always"
        name: {{ .Release.Name }}-www
        ports:
        - containerPort: 80
        - containerPort: 8080
        - containerPort: 9079
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 50m
            memory: 90Mi
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 60
          initialDelaySeconds: 240
          successThreshold: 1
          timeoutSeconds: 10
      restartPolicy: Always
