apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb
      product: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb
        product: {{ .Release.Name }}
      annotations:
        support.contact: "ace.innovation@dynatrace.com"
        support.channel: "#help-acebox"
    spec:
      containers:
      - image: dynatrace/easytravel-mongodb:{{ .Values.config.backend.tag }}
        imagePullPolicy: "Always"
        name: {{ .Release.Name }}-mongodb
        env:
        - name: DT_RELEASE_VERSION
          value: {{ .Values.config.mongodb.tag }}
        - name: DT_RELEASE_BUILD_VERSION
          value: {{ .Values.config.mongodb.tag }}
        - name: DT_RELEASE_STAGE
          value: {{ .Release.Namespace }}
        - name: DT_RELEASE_PRODUCT
          value: {{ .Release.Name }}
        ports:
        - containerPort: 27017
        - containerPort: 28017
        resources:
          limits:
            cpu: 300m
            memory: 150Mi
          requests:
            cpu: 200m
            memory: 110Mi
      restartPolicy: Always
