apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
      product: {{ .Release.Name }}
  replicas: {{ .Values.config.backend.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
        product: {{ .Release.Name }}
      annotations:
        support.contact: "ace.innovation@dynatrace.com"
        support.channel: "#help-acebox"
    spec:
      containers:
      - image: dynatrace/easytravel-backend:{{ .Values.config.backend.tag }}
        imagePullPolicy: "Always"
        name: {{ .Release.Name }}-backend
        env:
        - name: DT_RELEASE_VERSION
          value: {{ .Values.config.backend.tag }}
        - name: DT_RELEASE_BUILD_VERSION
          value: {{ .Values.config.backend.tag }}
        - name: DT_RELEASE_STAGE
          value: {{ .Release.Namespace }}
        - name: DT_RELEASE_PRODUCT
          value: {{ .Release.Name }}
        envFrom:
        - configMapRef:
            name: easytravel-config
        # - secretRef:
        #     name: mongo-credentials
        resources:
          limits:
            cpu: 200m
            memory: 768Mi
          requests:
            cpu: 50m
            memory: 512Mi
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /services/JourneyService/getLocations
            port: 8080
            scheme: HTTP
          periodSeconds: 30
          initialDelaySeconds: 120
          successThreshold: 1
          timeoutSeconds: 10  
      restartPolicy: Always
