---
- set_fact:
    monaco_projects_folder: "{{ role_path }}/files/monaco/projects"

- name: Source Private Synthetic Node ID
  include_role:
    name: dt-activegate
    tasks_from: source-node-id
  when: dt_synthetic_node_id is not defined 

- name: Easytravel - Apply Monitoring as Code
  include_role:
    name: monaco
    tasks_from: apply-monaco
    apply:
      environment:
        INGRESS_DOMAIN: "{{ ingress_domain }}"
        SYNTH_NODE_ID: "{{ dt_synthetic_node_id }}"
        APP_NAMESPACE: "{{ easytravel_namespace }}"
        INCL_SYNTH: "false"
  vars:
    monaco_project: "easytravel"
    monaco_projects_root: "{{ monaco_projects_folder }}" 