config:
    - health-easytravel-prod: "health-check-monitor.json"
    - health-easytravel-angular-prod: "health-check-monitor.json"
    - browser-easytravel-prod-home: "easytravel-browser-monitor.json"
    - browser-easytravel-angular-prod-home: "easytravel-browser-monitor.json"
  
health-easytravel-prod:
    - name: "webcheck.easytravel.prod"
    - url: "http://easytravel.{{ .Env.INGRESS_DOMAIN }}"
    - description: "Health Check for easytravel in prod"
    - location: "/infrastructure/synthetic-location/acebox.id"
    - managementZoneId: "/easytravel/management-zone/management-zone-easytravel.id"
    - tag: "/easytravel/auto-tag/tagging-easytravel-prod.name"
    - applicationId: "/easytravel/application-web/app-easytravel-prod.id"
    - frequencyInMin: "1"
    - enabled: "true"

health-easytravel-angular-prod:
    - name: "webcheck.easytravel-angular.prod"
    - url: "http://easytravel-angular.{{ .Env.INGRESS_DOMAIN }}"
    - description: "Health Check for easytravel-angular in prod"
    - location: "/infrastructure/synthetic-location/acebox.id"
    - managementZoneId: "/easytravel/management-zone/management-zone-easytravel.id"
    - tag: "/easytravel/auto-tag/tagging-easytravel-prod.name"
    - applicationId: "/easytravel/application-web/app-easytravel-angular-prod.id"
    - frequencyInMin: "1"
    - enabled: "true"

browser-easytravel-prod-home:
    - name: "browser.easytravel.prod.home"
    - url: "http://easytravel.{{ .Env.INGRESS_DOMAIN }}"
    - description: "Browser check for Easytravel Home Page"
    - location: "/infrastructure/synthetic-location/acebox.id"
    - managementZoneId: "/easytravel/management-zone/management-zone-easytravel.id"
    - tag: "/easytravel/auto-tag/tagging-easytravel-prod.name"
    - applicationId: "/easytravel/application-web/app-easytravel-prod.id"
    - frequencyInMin: "5"
    - enabled: "true"

browser-easytravel-angular-prod-home:
    - name: "browser.easytravel-angular.prod.home"
    - url: "http://easytravel-angular.{{ .Env.INGRESS_DOMAIN }}"
    - description: "Browser check for Easytravel Angular Home Page"
    - location: "/infrastructure/synthetic-location/acebox.id"
    - managementZoneId: "/easytravel/management-zone/management-zone-easytravel.id"
    - tag: "/easytravel/auto-tag/tagging-easytravel-prod.name"
    - applicationId: "/easytravel/application-web/app-easytravel-angular-prod.id"
    - frequencyInMin: "5"
    - enabled: "true"