config:
  ingress:
    class: public
    domain: "easytravel.mydomain.com"
    angular_domain: "easytravel-angular.mydomain.com"
  frontend:
    tag: "latest"
    replicas: "1"
  angular_frontend:
    tag: "latest"
    replicas: "1"
  backend:
    tag: "latest"
    replicas: "1"
  loadgen:
    #tag: "2.0.0.3256"
    tag: "latest"
    #problems: "BadCacheSynchronization,CPULoad,DatabaseCleanup,DatabaseSlowdown,FetchSizeTooSmall,JourneySearchError404,JourneySearchError500,LoginProblems,MobileErrors,TravellersOptionBox"
    problems: "DatabaseSlowdown"
    visitNumber: "5" #visits generated per minute
  loadgen_angular:
    tag: "latest"
    replicas: "1"
  www:
    tag: "latest"
    replicas: "1"
  mongodb:
    tag: "latest"
  pluginservice:
    tag: "latest"
